[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.20.0", features = ["extension-module"] }
rustc-hash = "1.1.0"
unicode-segmentation = "1.11.0"
